### ISSUE TITLE
Add link to open Work Item from list of linked work items

### ISSUE THREAD

**Issue by ErikEJ** [visualstudiogeeks/TagAdmin2015#1]
### Installed product versions
- Visual Studio: 2015 Ent
- This extension: [example 1.0.2]

**Comment by onlyutkarsh** [comment]
Hi @ErikEJ, Fair feedback and asked by many. Will work on it asap. Thank you!

**Comment by onlyutkarsh** [comment]
@ErikEJ this is fixed now. You will be able to click on workitem id and open the full workitem form. 
Please try this in the latest version which is now on [marketplace](https://marketplace.visualstudio.com/items?itemName=UtkarshShigihalliandTarunArora.TagAdminforVisualStudio2015). 

![image](https://cloud.githubusercontent.com/assets/2685029/21074591/932b95d8-bef4-11e6-94c6-8ed07e8fc0f5.png)
